Avocado\ExpensesBundle\Entity\Expenses:
  type: entity
  table: null
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    userid:
      type: integer
    time:
      type: datetime
    notes:
      type: text
    amount:
      type: float
  lifecycleCallbacks: {  }
