parameters:
#    expenses.example.class: Avocado\ExpensesBundle\Example

services:
#    expenses.example:
#        class: %expenses.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
