_user_bundle:
    resource: "@UserBundle/Resources/config/routing.yml"

ExpensesBundle:
    resource: "@ExpensesBundle/Resources/config/routing.yml"
    prefix:   /

WelcomeBundle:
    resource: "@WelcomeBundle/Resources/config/routing.yml"
    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
