<?php

namespace Avocado\ExpensesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ExpensesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExpensesRepository extends EntityRepository
{
}